import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const satoshi = localfont({
  src: [
    {
      path: "../../public/fonts/Satoshi-Regular.ttf",
    },
  ],
  variable: "--font-satoshi",
});
const Cabinet = localfont({
  src: [
    {
      path: "../../public/fonts/CabinetGrotesk-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-cabinet",
});

export const metadata = {
  title: "GITEX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${Cabinet.variable}`}>
        {children}
      </body>
    </html>
  );
}
